alias ...='cd ../..'
alias a='ack'
alias afind='ack-grep -il'
alias b='bundle'
alias be='bundle exec'
alias bi='bundle install'
alias bis='bundle install --binstubs'
alias bo='bundle open'
alias bs='bundle show'
alias bu='bundle update'
alias bx='bundle exec'
alias eod="ruby -e 't=Time.now; m=((Time.new(t.year,t.month,t.day,18,0,0)-t)/60).ceil.to_s; puts \"Go home in #{m} minutes\"'"
alias foreman='nocorrect foreman'
alias g='git'
alias git='hub'
alias gti='git'
alias history='fc -l 1' # show history
alias la='ls -lA'
alias ll='ls -l'
alias lsa='ls -lah'
alias lunch="ruby -e 't=Time.now; m=((Time.new(t.year,t.month,t.day,12,0,0)-t)/60).ceil.to_s; puts \"Hunger Satisfied in #{m} minutes\"'"
alias orb='irb'
alias pg='psql -h localhost -U bj'
alias po='popd'
alias pu='pushd'
alias r='noglob rake'
alias railz='PB_CLIENT_TYPE=zmq PB_IGNORE_DEPRECATIONS=1 bin/rails s'
alias ri='noglob ri'
alias rspec='nocorrect rspec'
alias s='PB_IGNORE_DEPRECATIONS=1 RAILS_ENV=test bx rake spec'
alias sb='nocorrect sb'
alias sl='ls' # often screw this up
alias sourcezsh='source ~/.zshrc'
alias track="osascript /code/src/scripts/itunes_current_track.scpt"
alias v='vim'
alias vim=/usr/local/bin/vim
alias vzsh='vim ~/.zshrc'
alias wifioff='networksetup -setairportpower en0 off'
alias wifion='networksetup -setairportpower en0 on'
