#!/bin/sh
rm -f .git/*tags
/usr/local/bin/ctags --tag-relative -Rf.git/tags --exclude=.git --languages=-javascript,sql
/usr/local/bin/ctags --tag-relative -Rf.git/javascript.tags --exclude=.git --languages=javascript
/bin/cp .git/javascript.tags .git/javascript.jsx.tags

